<?php

function motor_menu() {

  $items['dashboard'] = array(
    'title' => 'Dashboard',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('motor_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );

  $items['dashboard'] = array(
    'title' => 'Dashboard',
    'page callback' => 'motor_dashboard',
    'access callback' => 'motor_search_owner_permission',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
  );

  $items['ajax/search-owner/%'] = array(
    'access arguments' => array('access administration pages'),
    'page callback' => 'motor_search_owner',
    'access callback' => 'motor_search_owner_permission',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
  );

  $items['ajax/custom-ac'] = array(
    'access arguments' => array('access administration pages'),
    'page callback' => 'motor_custom_autocomplete',
    'access callback' => 'motor_search_owner_permission',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function motor_init() {
  $path = parse_url(request_uri(), PHP_URL_PATH);

  $path_elements = explode('/', $path);
  array_pop($path_elements);
  $path_without_last = implode('/', $path_elements);

  drupal_add_js(drupal_get_path('module', 'motor') . '/js/script.js');

  if ($path_without_last == '/node/add/event-treatment') {
    drupal_add_library('system', 'ui.autocomplete');
    
    // Pass terms from vocabs for js autocomplete.
    $treatment_vocabs = array(
      'field_anamnesis' => 'treatments_anamnesis',
      'field_preset_state' => 'treatments_present_state',
      'field_diagnosis' => 'treatments_diagnosis',
      'field_complementary' => 'treatments_complementary',
      'field_notes' => 'treatments_notes',
      'field_operation' => 'treatments_operation',
    );

    foreach ($treatment_vocabs as $vocab) {
      $terms = motor_taxonomy_terms_to_jsautocomplete($vocab);
      drupal_add_js($terms, 'setting');
    }
    
    $terms_complementary = motor_taxonomy_terms_to_jsautocomplete('treatments_complementary');
    drupal_add_js($terms_complementary, 'setting');

    $terms_notes = motor_taxonomy_terms_to_jsautocomplete('treatments_notes');
    drupal_add_js($terms_notes, 'setting');


    drupal_add_js(drupal_get_path('module', 'motor') . '/js/motor_autocomplete.js');
    drupal_add_css(drupal_get_path('module', 'motor') . '/css/motor_autocomplete.css');
  }

  if ($path === '/dashboard' || $path === '/') {
    drupal_add_js(drupal_get_path('module', 'motor') . '/js/dashboard.js');
    $settings = array(
      'path' => drupal_get_path('module', 'motor'),
   );
    
  }

}

function motor_search_owner_permission() {
  global $user;
  if ($user->uid > 0) {
    return TRUE;
  }

  return FALSE;
}

function motor_search_node($search_phrase) {
  $query = db_select('node', 'n')
  ->fields('n', array('nid', 'title', 'type'))
  ->condition('n.title', '%' . db_like($search_phrase) . '%', 'LIKE')
  ->orderBy('n.title', 'ASC')
  ->range(0,10);

  $results = $query
  ->execute()
  ->fetchAll();

  foreach ($results as $row) { 
    if ($row->type == 'pet') {
      $query = db_select('field_data_field_pets', 'p')
      ->fields('p', array('entity_id'))
      ->condition('p.field_pets_nid', $row->nid)
      ->range(0,1);

      $results = $query
      ->execute()
      ->fetchAll();

      $row->nid = $results[0]->entity_id;
    }
    
    $nids[] = (int)$row->nid;
  }

  return $nids;
}

function motor_form($form, &$form_state) {

  $form['search_phrase'] = array(
    '#title' => t('Search'),
    '#description' => t('Search for owners and pets by tehir name, address, etc.'),
    '#type' => 'textfield',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );

  if (isset($form_state['storage'])) {
    $form['output'] = array(
      '#markup' => $form_state['storage']['output'],
    );
  }

  $form['search_results'] = array(
    '#markup' => '<div id="search-results-owners"></div>' . '<div id="search-results-pets"></div>',
  );


  return $form;
}

function motor_form_submit($form, &$form_state) {
}

function motor_search_owner($search_phrase) {
  $nids = motor_search_node($search_phrase);
  print views_embed_view('owners', 'page', implode(',', $nids));
}

function motor_dashboard() {
  $output = file_get_contents(drupal_get_path('module', 'motor') . '/templates/dashboard.tpl.php');
  $output = str_replace('###serach-results###', views_embed_view('owners', 'page'), $output); 
  return $output;
}

function motor_block_info() {
  $blocks = array();
  
  $blocks['vaccinate'] = array(
    'info' => t('Vaccinate'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['treatment'] = array(
    'info' => t('Treatment'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['loggedin_user'] = array(
    'info' => t('Logged in user'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['drug_on_stock'] = array(
    'info' => t('Drug on stock'),
    'cache' => DRUPAL_NO_CACHE,
  );


  return $blocks;
}

function motor_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'vaccinate':
      if (user_access('access content')) {
          $block['subject'] = t('Vaccinate');
          $block['content'] = l(t('New vaccinate'), '/node/add/event-vaccinate/' . arg(1), array(
            'attributes' => array(
              'id' => 'vaccinate',
              'class' => array('add-event'),
            ),
          )) . '<div id="former-vaccinates">' . views_embed_view('former_vaccinates', 'default', arg(1)) . '</div>';
      }
      else {
          $block['content'] = t('No content available.');
      }
    break;

    case 'treatment':
      if (user_access('access content')) {
          $block['subject'] = t('Treatment');
          $block['content'] = l(t('New treatment'), '/node/add/event-treatment/' . arg(1), array(
            'attributes' => array(
              'id' => 'treatment',
              'class' => array('add-event'),
            ),
          )) . '<div id="former-treatments">' . views_embed_view('former_treatments', 'default', arg(1)) . '</div>';
      }
      else {
          $block['content'] = t('No content available.');
      }
    break;

    case 'loggedin_user':
      global $user;
      $name = '';
      if (isset($user->name)) {
        $name = $user->name;
      

        $block['content'] = t('@name (@userid) logged in', array(
          '@name' => $name,
          '@userid' => '#' . $user->uid,
        ));
      }
    break;

    case 'drug_on_stock':
      $sum = motor_drug_stock_get(arg(1));
      $block['content'] = t('On stock:') . $sum;
      
    break;
  }
  return $block;
}

function motor_node_presave($node) {
  if ($node->type == 'event_treatment' || $node->type == 'event_vaccinate') {
    if (!isset($node->field_pet[LANGUAGE_NONE][0]['nid'])) {
      $node->field_pet[LANGUAGE_NONE][0]['nid'] = arg(3);
    }
  }

  if ($node->type == 'event_treatment') {
    if (!empty($node->field_anamnesis[LANGUAGE_NONE])) {
      $terms = explode(',', $node->field_anamnesis[LANGUAGE_NONE][0]['value']);
      foreach ($terms as $term) {
        $term = trim($term);
        motor_save_new_term($term, 'treatments_anamnesis');
      }
    }
  }
}

function motor_taxonomy_terms_to_jsautocomplete($voc) {
  $vocabulary = taxonomy_vocabulary_machine_name_load($voc);
  $terms = entity_load('taxonomy_term', FALSE, array('vid' => $vocabulary->vid));

  $terms_refactored = [];
  foreach ($terms as $term) {
    $terms_refactored[] = $term->name;
  }
  return array($voc => $terms_refactored);
}

function motor_save_new_term($termName, $vocabName) {

  $termObj = taxonomy_get_term_by_name($termName, $vocabName);
  if (empty($termObj)) {
    $vocabObj = taxonomy_vocabulary_machine_name_load($vocabName);
 
    $term = (object) array(
     'name' => $termName,
     'vid' => $vocabObj->vid,
    );

    taxonomy_term_save($term);
  } else {
    $term = reset($termObj);
  }

  return $term->tid;

}

function motor_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'event_treatment_node_form') {
    $treatment_vocabs = array(
      'field_anamnesis' => 'treatments_anamnesis',
      'field_present_state' => 'treatments_present_state',
      'field_diagnosis' => 'treatments_diagnosis',
      'field_complementary' => 'treatments_complementary',
      'field_notes' => 'treatments_notes',
      'field_operation' => 'treatments_operation',
    );

    foreach ($treatment_vocabs as $key => $voc) {
      $form[$key][LANGUAGE_NONE][0]['value']['#attributes'] = array(
        'data-voc' => $voc,
      );
    }

    $form['actions']['submit']['#submit'][] = 'motor_add_treatment_custom_submit';

  }
}

function motor_add_treatment_custom_submit($form, &$form_state) {
  $nid = $form_state['values']['field_pet'][LANGUAGE_NONE][0]['nid'];
  unset($_GET['destination']);
  unset($_REQUEST['edit']['destination']); 
  $form_state['redirect'] = '/node/' . $nid;
}

function motor_drug_stock_get($nid) {
  $query = db_select('field_data_field_drug_qty', 'dq')
  ->fields('dq', array('field_drug_qty_value'))
  ->condition('dq.bundle', 'drug_supply');
  $query->leftJoin('field_data_field_drug', 'd', 'd.entity_id = dq.entity_id');
  $query->condition('d.field_drug_nid', $nid);

  $results = $query
  ->execute()
  ->fetchAll();

  $sum = 0;
  foreach ($results as $row) {
    $sum += $row->field_drug_qty_value;
  }

  $query = db_select('field_data_field_drug_qty', 'dq')
  ->fields('dq', array('field_drug_qty_value'))
  ->condition('dq.bundle', 'drugs_used');
  $query->leftJoin('field_data_field_drug', 'd', 'd.entity_id = dq.entity_id');
  $query->condition('d.field_drug_nid', $nid);

  $results = $query
  ->execute()
  ->fetchAll();

  foreach ($results as $row) {
    $sum -= $row->field_drug_qty_value;
  }

  return $sum;
}

function motor_get_drugs_used_on_treatment($nid) {
  $query = db_select('field_data_field_drugs_used', 'du')
  ->fields('d', array('field_drug_nid'))
  ->fields('dq', array('field_drug_qty_value'))
  ->fields('dsp', array('field_selling_price_value'))
  ->fields('dn', array('title'))
  ->condition('dq.bundle', 'drugs_used');
  $query->leftJoin('field_data_field_drug', 'd', 'd.entity_id = du.field_drugs_used_value');
  $query->leftJoin('field_data_field_drug_qty', 'dq', 'dq.entity_id = du.field_drugs_used_value');
  $query->leftJoin('field_data_field_selling_price', 'dsp', 'dsp.entity_id = d.field_drug_nid');
  $query->leftJoin('node', 'dn', 'd.field_drug_nid = dn.nid');
  $query->condition('du.entity_id', $nid);

  $results = $query
  ->execute()
  ->fetchAll();

  $output = [];
  foreach ($results as $row) {
    $sum_price = $row->field_selling_price_value * $row->field_drug_qty_value;
    $output[] = $row->title . ': ' . $row->field_selling_price_value . 'HUF x ' . $row->field_drug_qty_value . ' - ' . $sum_price . 'HUF';
  }

  return '<div class="drugs-used-list">' . implode('<br />', $output) . '</div>';
}

function motor_calculate_treatment_sum_price($nid) {
  $query = db_select('field_data_field_drugs_used', 'du')
  ->fields('d', array('field_drug_nid'))
  ->fields('dq', array('field_drug_qty_value'))
  ->fields('dsp', array('field_selling_price_value'))
  ->fields('dn', array('title'))
  ->condition('dq.bundle', 'drugs_used');
  $query->leftJoin('field_data_field_drug', 'd', 'd.entity_id = du.field_drugs_used_value');
  $query->leftJoin('field_data_field_drug_qty', 'dq', 'dq.entity_id = du.field_drugs_used_value');
  $query->leftJoin('field_data_field_selling_price', 'dsp', 'dsp.entity_id = d.field_drug_nid');
  $query->leftJoin('node', 'dn', 'd.field_drug_nid = dn.nid');
  $query->condition('du.entity_id', $nid);

  $results = $query
  ->execute()
  ->fetchAll();

  $sum = 0;
  foreach ($results as $row) {
    $sum += $row->field_selling_price_value * $row->field_drug_qty_value;
  }

  $treatment = node_load($nid);

  if (isset($treatment->field_cost_of_treatment[LANGUAGE_NONE])) {
    $sum += $treatment->field_cost_of_treatment[LANGUAGE_NONE][0]['value'];
  }

  return $sum;
}
